### ISSUE TITLE
Need an update to the example files

### ISSUE THREAD

**Issue by ShawnHouCHN** [cloudera-labs/envelope#20]
Hi Author
It is wonderful that the new version 4 is compatible with spark 2 and kafka 0.10 
I once downloaded the package and tried out the examples you include, seems the foutput (https://github.com/cloudera-labs/envelope/blob/master/src/main/java/com/cloudera/labs/envelope/output/FileSystemOutput.java) only support parquet and csv rather than, as the example conf shown, avro.  Might need a review on this part. Thx

**Comment by jeremybeard** [comment]
This is now fixed.
