### ISSUE TITLE
spaces in fields name

### ISSUE THREAD

**Issue by matteoarrigoni81** [cloudera-labs/envelope#27]
Hi, I'm trying to use envelope to read one csv file and, after some checks on fields format, write two csv files: the first one with "ok data" and the second one with "ko data". My csv source has fields names on 1st row but these names contain spaces. How can I make a "select [field 1], [field 2] from StepOfChecks where..." by query.literal ? Thanks
P.s.: I'm not sure that this is the right way to make questions... in case, redirect me, thanks.

**Comment by jeremybeard** [comment]
Hi there, for now the best place to ask questions is on the Cloudera Community forum here: http://community.cloudera.com/t5/Cloudera-Labs/bd-p/ClouderaLabs
